services:
  - type: web
    name: solana-game-life
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: ALICIZATION_PLUGINS
        value: ""
      - key: ALICIZATION_TOWN_NPC_ENABLED
        value: "true"
